[book]
authors = ["Milo"]
language = "en"
multilingual = false
src = "guide"
title = "Rust Notebooks"

[output.html.playground]
editable = true
line-numbers = true

[output.html]
git-repository-url = "https://github.com/Milo123459/rust-notebooks/tree/master/guide"
edit-url-template = "https://github.com/Milo123459/rust-notebooks/edit/master/guide/{path}"